### ISSUE TITLE
HelloSearchAttributes broken

### ISSUE THREAD

**Issue by mfateev** [temporalio/temporal-java-samples#10]
```
7:33:50 PM: Executing task 'HelloSearchAttributes.main()'...

:googleJavaFormat NO-SOURCE
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:HelloSearchAttributes.main()Exception in thread "main" io.grpc.StatusRuntimeException: INVALID_ARGUMENT: 2020-05-22T19:33:51.841 is not a valid search attribute value for key CustomDatetimeField
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:244)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:225)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:142)
	at io.temporal.proto.workflowservice.WorkflowServiceGrpc$WorkflowServiceBlockingStub.startWorkflowExecution(WorkflowServiceGrpc.java:2601)
	at io.temporal.internal.external.GenericWorkflowClientExternalImpl.lambda$startWorkflowInternal$0(GenericWorkflowClientExternalImpl.java:155)
	at io.temporal.internal.common.GrpcRetryer.retryWithResult(GrpcRetryer.java:127)
	at io.temporal.internal.external.GenericWorkflowClientExternalImpl.startWorkflowInternal(GenericWorkflowClientExternalImpl.java:153)
	at io.temporal.internal.external.GenericWorkflowClientExternalImpl.startWorkflow(GenericWorkflowClientExternalImpl.java:88)
	at io.temporal.internal.sync.WorkflowStubImpl.startWithOptions(WorkflowStubImpl.java:130)
	at io.temporal.internal.sync.WorkflowStubImpl.start(WorkflowStubImpl.java:217)
	at io.temporal.internal.sync.WorkflowInvocationHandler.startWorkflow(WorkflowInvocationHandler.java:185)
	at io.temporal.internal.sync.WorkflowInvocationHandler.access$300(WorkflowInvocationHandler.java:45)
	at io.temporal.internal.sync.WorkflowInvocationHandler$SyncWorkflowInvocationHandler.startWorkflow(WorkflowInvocationHandler.java:306)
	at io.temporal.internal.sync.WorkflowInvocationHandler$SyncWorkflowInvocationHandler.invoke(WorkflowInvocationHandler.java:262)
	at io.temporal.internal.sync.WorkflowInvocationHandler.invoke(WorkflowInvocationHandler.java:172)
	at com.sun.proxy.$Proxy5.getGreeting(Unknown Source)
	at io.temporal.samples.hello.HelloSearchAttributes.main(HelloSearchAttributes.java:122)
7:34:03 PM: Task execution finished 'HelloSearchAttributes.main()'.

```

**Comment by mfateev** [comment]
Fixed by https://github.com/temporalio/temporal-java-samples/pull/13
